//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using Entities;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_Gestion_TurnosEntities : DbContext
    {
        public DB_Gestion_TurnosEntities()
            : base("name=DB_Gestion_TurnosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Persons> Tbl_Persons { get; set; }
        public virtual DbSet<Tbl_Positions> Tbl_Positions { get; set; }
        public virtual DbSet<Tbl_Services> Tbl_Services { get; set; }
        public virtual DbSet<tbl_turn_position> tbl_turn_position { get; set; }
        public virtual DbSet<Tbl_Turns> Tbl_Turns { get; set; }
        public virtual DbSet<Tbl_Company> Tbl_Company { get; set; }
        public virtual DbSet<Tbl_Configuration> Tbl_Configuration { get; set; }
    }
}
