//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Configuration
    {
        public int configurationID { get; set; }
        public string configurationColorBarHeader { get; set; }
        public string configurationColorBarFooter { get; set; }
        public string configurationBarHeaderTable { get; set; }
        public string configurationColorTableBody { get; set; }
        public string configurationMessage { get; set; }
        public byte[] configurationImage { get; set; }
        public string configurationVideoURL { get; set; }
        public Nullable<int> companyID { get; set; }
    }
}
