//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_turn_position
    {
        public int turn_positionID { get; set; }
        public int turnID { get; set; }
        public int positionID { get; set; }
        public Nullable<System.DateTime> createOn { get; set; }
    }
}
