//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public int userID { get; set; }
        public string userUsername { get; set; }
        public string userPassword { get; set; }
        public System.DateTime createOn { get; set; }
        public Nullable<int> idPerson { get; set; }
        public Nullable<int> idCompany { get; set; }
    }
}
